name: Deploy Next.js to VPS

on:
   push:
      branches:
         - master # деплой по пушу в master

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup SSH access
           run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

         - name: Deploy to VPS
           run: |
              ssh -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              cd /root/Alive-Water/alivewater &&
              git pull origin master &&
              npm ci >> deploy.log 2>&1 &&
              NODE_OPTIONS=--max_old_space_size=256 npm run build >> deploy.log 2>&1 &&
              pm2 restart alivewater >> deploy.log 2>&1
              "
